votes/urls.py
from django.conf.urls import patterns, include, url
from django.views.static import serve as serve_static
from django.contrib.auth.views import login as view_login, logout as view_logout
from votes import views

from votes_ensimag import settings

urlpatterns = [
    # Examples:
    # url(r'^$', 'votes_ensimag.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    # url(r'^$', views.termine, name='index'),
    url(r'^$', views.index, name='index'),
    url(r'^bulletin$', views.bulletin, name='bulletin'),
    url(r'^contact$', views.contact, name='contact'),
    url(r'^login$', view_login, name='login'),
    url(r'^logout$', view_logout, {'next_page': '/votes'}, name='logout'),
]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += [ url(r'^media/(?P<path>.*)$', serve_static, { 'document_root': settings.MEDIA_ROOT }) ]

votes_ensimag/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.shortcuts import redirect
from django.views.static import serve as serve_static

from votes_ensimag import settings

urlpatterns = [
    # Examples:
    # url(r'^$', 'votes_ensimag.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', lambda r : redirect('votes/')),
    url(r'^votes/', include('votes.urls', namespace='votes')),
    url(r'^admin/', include(admin.site.urls)),
]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += [ url(r'^media/(?P<path>.*)$', serve_static, {'document_root': settings.MEDIA_ROOT}) ]

admin.site.site_header = 'Votes campagne Ensimag'
admin.site.site_title = 'Votes campagne Ensimag'

votes/models.py
# coding=utf-8
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
from django.utils.html import format_html

# Représente un type de liste : BDE, BDA, BDS...
# nom : nom du type
# deux_tours : booléen qui indique s'il y aura deux tours pour ce type de liste
class TypeListe(models.Model):

    nom = models.CharField(max_length=10, verbose_name='Nom du type')
    deux_tours = models.BooleanField(default=False, verbose_name='Deux tours requis ?')

    def __str__(self):
        return self.nom

# Représente une liste
class Liste(models.Model):

    type = models.ForeignKey(TypeListe, verbose_name='Type de liste')
    nom = models.CharField(max_length=50, verbose_name='Nom')
    liste_logo = models.ImageField(upload_to='logos', blank=True, verbose_name='Logo')
    liste_couleur = models.CharField(max_length=7, default='#000', verbose_name='Couleur (hexa)')
    est_vote_blanc = models.BooleanField(default=False, verbose_name='Vote blanc')


    class Meta:
        ordering = ['type', 'nom']

    def __str__(self):
        return "{} ({})".format(self.nom, self.type)

    # Utilisé pour dessiner un rectangle de la couleur de la liste en CSS
    def color_box(self):
        return format_html('<div id="rectange_couleur" style="background-color: {}; width:80px; height:15px; border-radius:5px;"></div>'.format(self.liste_couleur))
    color_box.short_description = 'Couleur'

    # Renvoie l'url du logo si spécifiée ou le logo par défaut sinon
    def logo(self):
        if self.liste_logo and hasattr(self.liste_logo, 'url'):
            return self.liste_logo.url
        else:
            return '/media/logos/blank.png'
    logo.short_description = 'Logo'

    # Nombre de votes obtenus au premier tour
    # déterminé par un count sur les votes
    def get_nombre_votes_1(self):
        return Vote.objects.filter(liste=self, est_second_tour=False).count()
    get_nombre_votes_1.short_description = '# votes tour 1'

    # Nombre de votes obtenus au second tour
    # déterminé par un count sur les votes
    def get_nombre_votes_2(self):
        return Vote.objects.filter(liste=self, est_second_tour=True).count()
    get_nombre_votes_2.short_description = '# votes tour 2'

class Votant(models.Model):
    prenom = models.CharField(max_length=100, verbose_name='Prénom')
    nom = models.CharField(max_length=100, verbose_name='Nom')
    annee = models.CharField(max_length=2, verbose_name='Année')
    login = models.CharField(max_length=8, verbose_name='Login')
    apprenti = models.BooleanField(default=False, verbose_name='Apprenti')
    phelmag = models.BooleanField(default=False, verbose_name='Phelmag')
    a_vote = models.BooleanField(default=False, verbose_name='A voté')

    # Pour le lien avec les utilisateurs Django, non modifiable depuis l'admin
    user = models.OneToOneField(User, null=True, blank=True, verbose_name='Utilisateur associé', editable=False)

    class Meta:
        ordering = ['annee', 'nom']

    def __str__(self):
        return self.login

# Vote pour une liste
# On lie la liste et le votant et on enregistre l'IP et la date.
# est_second_tour indique si le vote est pour un second tour.
class Vote(models.Model):
    liste = models.ForeignKey(Liste, verbose_name='Liste')
    votant = models.ForeignKey(Votant, verbose_name='Votant', null=True)
    ip = models.GenericIPAddressField(verbose_name='Adresse IP')
    date = models.DateTimeField(verbose_name='Date et heure')
    est_second_tour = models.BooleanField(default=False, verbose_name='Second tour')

    def __str__(self):
        return '({0} -> {1} on {2} with IP {3})'.format(self.votant, self.liste, self.date, self.ip)

    # Affichage en couleur du nom de la liste dans la zone d'admin
    def color_liste(self):
        return format_html('<span style="color: {};">{}</span>'.format(self.liste.liste_couleur, self.liste.nom))
    color_liste.short_description = 'Nom'

    # Raccourci pour le type de liste
    def vote_type(self):
        return self.liste.type
    vote_type.short_description = 'Type de vote'

votes/forms.py
# coding=utf-8
from django import forms
from django.core.exceptions import ValidationError

from votes.models import *

class VoteForm(forms.Form):

    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        types_liste = TypeListe.objects.all()
        self.user = user
        for t in types_liste:
            self.fields["{}_1".format(t.nom)] = forms.ModelChoiceField(Liste.objects.filter(type=t), widget=forms.RadioSelect, empty_label=None, label="Choix {}".format(t.nom))
            if t.deux_tours:
                self.fields["{}_2".format(t.nom)] = forms.ModelChoiceField(Liste.objects.filter(type=t), widget=forms.RadioSelect, empty_label=None, label="Second tour {}".format(t.nom))
        self.fields["confirm_box"] = forms.BooleanField(label="Je confirme mon vote.", required=True)

    def clean(self):
        # Données nettoyées
        cleaned_data = super(VoteForm, self).clean()
        self.fields.pop('confirm_box', None)

        # Vérifications supplémentaires sur l'utilisateur
        try:
            votant = Votant.objects.get(login=self.user.username)
            if votant.a_vote:
                raise ValidationError("Vous avez déjà voté !")
        except Votant.DoesNotExist:
            raise ValidationError("Cet utilisateur n'est pas un votant valide !")

        # Vérification des choix de vote

        # Construction de l'association (type de liste) -> (ensemble de listes)
        try:
            listes = {cleaned_data[f].type: [] for f in self.fields}
        except KeyError:
            raise ValidationError("Tous les champs doivent être remplis !")

        for f in self.fields:
            listes[cleaned_data[f].type].append(cleaned_data[f])

        for tl in listes:
            # On vérifie que le nombre de vote pour un type donné est cohérent
            if (tl.deux_tours and len(listes[tl]) != 2) or (not tl.deux_tours and len(listes[tl]) != 1):
                raise ValidationError("Mauvais nombre de votes pour l'élection {}.".format(tl.nom))

            # On vérifie que s'il y a deux tours on ne vote pas deux fois pour la même liste
            if tl.deux_tours:
                # Variables intermédiaires qui représentent les listes
                liste_1 = listes[tl][0]
                liste_2 = listes[tl][1]
                # Deux entrées en base qui ont la même clé primaire sont égales. Cependant, on peut voter blanc aux deux tours !
                if (not (liste_1.est_vote_blanc or liste_2.est_vote_blanc)) and (liste_1.pk == liste_2.pk):
                    raise ValidationError("Impossible de voter deux fois pour la même liste.")

votes/views.py
# coding=utf-8
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from votes.models import *
from votes.forms import *

import datetime

# Create your views here.

def index(request):
    listes = Liste.objects.filter(est_vote_blanc=False).order_by('type')
    context = {'listes': listes}
    return render(request, 'index.html', context)

def termine(request):
    return render(request, 'termine.html')

@login_required
def bulletin(request):
    listes = Liste.objects.filter(est_vote_blanc=False).order_by('type')
    if request.method == 'POST':
        form = VoteForm(request.user, request.POST)
        if form.is_valid():
            # On marque le votant associé à l'utilisateur comme ayant voté
            votant = Votant.objects.get(login=request.user.username)
            votant.a_vote = True
            votant.save()

            # On sauvegarde les votes en base

            # IP du votant
            x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')

            if x_forwarded_for:
                ipaddress = x_forwarded_for.split(',')[-1].strip()
            else:
                ipaddress = request.META.get('REMOTE_ADDR')

            # Support non assuré pour les votes à deux tours !
            form.cleaned_data.pop('confirm_box', None)
            for f in form.cleaned_data:
                vote = Vote.objects.create(liste=form.cleaned_data[f], votant=votant, ip=ipaddress, date=datetime.datetime.now(), est_second_tour=False)

            return render(request, 'succes.html')
        else:
            form.fields["confirm_box"] = forms.BooleanField(label="Je confirme mon vote.", required=True)
            return render(request, 'bulletin.html', {'form' : form, 'listes' : listes})
    else:
        form = VoteForm(request.user)
        context = {'form' : form, 'listes' : listes}
        return render(request, 'bulletin.html', context)

def contact(request):
    context = {}
    return render(request, 'contact.html', context)

votes/templates/base.html
{% extends 'bootstrap.html' %}

{% load bootstrap3 %}

{% block bootstrap3_content %}
    <div class="container">
        <h1>{% block title %}(no title){% endblock %}</h1>

        {% bootstrap_messages %}

        {% block content %}(no content){% endblock %}
    </div>

{% endblock %}

votes/templates/bootstrap.html
<!DOCTYPE html>

{% load bootstrap3 %}
<html{% if request.LANGUAGE_CODE %} lang="{{ request.LANGUAGE_CODE }}"{% endif %}>

<head>
    <meta charset="utf-8">
    <!--[if IE]><meta http-equiv="X-UA-Compatible" content="IE=edge" /><![endif]-->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block bootstrap3_title %}Titre{% endblock %}</title>
    {% bootstrap_css %}
    <style type="text/css">
        body {
            padding-top: 65px;
        }
    </style>
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    {% if 'javascript_in_head'|bootstrap_setting %}{% bootstrap_javascript jquery=True %}{% endif %}
    {% block bootstrap3_extra_head %}{% endblock %}
</head>

<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href={% url 'votes:index' %}>Campagne Ensimag</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><a href={% url 'votes:index' %}>Accueil</a></li>
            <li><a href={% url 'votes:bulletin' %}>Bulletin de vote</a></li>
            <li><a href={% url 'votes:contact' %}>Contact</a></li>
          </ul>
          {% if user.is_authenticated %}
          <ul class="nav navbar-nav navbar-right">
            <li><p class="navbar-text">Connecté en tant que <b>{{ user.username }}</b></p></li>
            <li><a href={% url 'votes:logout' %}>Déconnexion</a></li>
          </ul>
          {% else %}
          <ul class="nav navbar-nav navbar-right">
            <li><a href={% url 'votes:login' %}>Connexion</a></li>
          </ul>
          {% endif %}
        </div><!--/.nav-collapse -->
      </div>
    </nav>
<div class="container">
{% block bootstrap3_content %}Contenu{% endblock %}
</div>
{% if not 'javascript_in_head'|bootstrap_setting %}{% bootstrap_javascript jquery=True %}{% endif %}
{% block bootstrap3_extra_script %}{% endblock %}
</body>

</html>

votes/templates/bulletin.html
{% extends 'base.html' %}

{% load bootstrap3 %}

{% block bootstrap3_title %}
Bulletin de vote en ligne
{% endblock %}

{% block bootstrap3_content %}
{% for liste in listes %}
<div class="col-xs-3"><img src="{{ liste.logo }}" alt="{{ liste.nom }}" class="center-block" style="max-width:40%; heigth:auto;"></div>
{% endfor %}
<div class="page-header">
<h1>Bulletin de vote en ligne</h1>
</div>
<form method="post" action="{% url 'votes:bulletin' %}">
    <p>Sélectionnez vos choix de vote.</p><p><em style="color:#E81515;">Attention : le vote est irréversible et effectif dès envoi du bulletin.</em></p>
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
        <button class="btn btn-lg btn-primary" type="submit" value="voter">Voter</button>
    {% endbuttons %}
    <input type="hidden" name="next" value="{{ next }}" />
</form>
{% endblock %}

votes/templates/contact.html
{% extends 'base.html' %}

{% load bootstrap3 %}

{% block bootstrap3_title %}
Vote en ligne Campagne Ensimag
{% endblock %}

{% block bootstrap3_extra_head %}
    <link href="http://getbootstrap.com/dist/css/bootstrap-theme.min.css" rel="stylesheet">
{% endblock %}

{% block bootstrap3_content %}
<div class="page-header">
<h1>Informations de contact</h1>
</div>
    <p>En cas de difficultés avec le site, contacter Mehdi Bahri</p>
    <ul>
    <li>Tél. 06 42 66 10 12</li>
    <li>Mél. mehdi.bahri@ensimag.grenoble-inp.fr</li>
    </ul>
{% endblock %}

votes/templates/echec.html
{% extends 'base.html' %}

{% load bootstrap3 %}

{% block bootstrap3_title %}
Echec du vote{% endblock %}

{% block bootstrap3_content %}
<div class="page-header">
<h1>Bulletin de vote en ligne</h1>
</div>
    Votre vote n'a pas été enregistré, réessayez.
{% endblock %}

votes/templates/index.html
{% extends 'base.html' %}

{% load bootstrap3 %}

{% block bootstrap3_title %}
Vote en ligne Campagne Ensimag
{% endblock %}

{% block bootstrap3_extra_head %}
    <link href="http://getbootstrap.com/dist/css/bootstrap-theme.min.css" rel="stylesheet">
{% endblock %}

{% block bootstrap3_content %}
<div class="jumbotron">
<h1>Vote en ligne Campagne Ensimag</h1>
<p>Bienvenue sur le système de vote en ligne pour la campagne Ensimag</p>
</div>
{% for liste in listes %}
<div class="col-xs-3 col-md-3"><img src="{{ liste.logo }}" alt="{{ liste.nom }}" class="img-responsive center-block"><p style="text-align:center;">{{ liste.nom }}</p></div>
{% endfor %}
{% endblock %}

votes/templates/not_yet.html
<!DOCTYPE html>

{% load bootstrap3 %}
<html{% if request.LANGUAGE_CODE %} lang="{{ request.LANGUAGE_CODE }}"{% endif %}>

<head>
    <meta charset="utf-8">
    <!--[if IE]><meta http-equiv="X-UA-Compatible" content="IE=edge" /><![endif]-->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Vote pour la campagne Ensimag</title>
    {% bootstrap_css %}
    <style type="text/css">
        body {
            padding-top: 65px;
        }
    </style>
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    {% if 'javascript_in_head'|bootstrap_setting %}{% bootstrap_javascript jquery=True %}{% endif %}
    {% block bootstrap3_extra_head %}{% endblock %}
</head>

<body>
<div class="container">
<h1>La période de vote commence à {{ date.time }}.</h1>
</div>
</body>
</html>

votes/templates/succes.html
{% extends 'base.html' %}

{% load bootstrap3 %}

{% block bootstrap3_title %}
Vote pris en compte{% endblock %}

{% block bootstrap3_content %}
<div class="page-header">
<h1>Bulletin de vote en ligne</h1>
</div>
    Votre vote a bien été enregistré.
{% endblock %}

votes/templates/termine.html
<!DOCTYPE html>

{% load bootstrap3 %}
<html{% if request.LANGUAGE_CODE %} lang="{{ request.LANGUAGE_CODE }}"{% endif %}>

<head>
    <meta charset="utf-8">
    <!--[if IE]><meta http-equiv="X-UA-Compatible" content="IE=edge" /><![endif]-->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Vote clos</title>
    {% bootstrap_css %}
    <style type="text/css">
        body {
            padding-top: 65px;
        }
    </style>
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    {% if 'javascript_in_head'|bootstrap_setting %}{% bootstrap_javascript jquery=True %}{% endif %}
    {% block bootstrap3_extra_head %}{% endblock %}
</head>

<body>
<div class="container">
<h1>Le vote s'est terminé à 17h00.</h1>
</div>
</body>
</html>